### ISSUE TITLE
InternalServerErrorException: http: Hijack is incompatible with use of CloseNotifier

### ISSUE THREAD

**Issue by foxlegend** [arquillian/arquillian-cube#310]
Hello there,

I had a new issue when building the image with Cube.
In fact, it seems to be a known issue with docker itself I could not explain.

When building an image, Cube seems to perform the following Docker API queries:

* ping (OK),
* build the image with Dockerfile directory content (OK),
* create the container (OK),
* start the container (OK),
* inspect the container (OK),
* create the await command `ss -lntu | grep … etc.` (OK),
* execute the command (KO).

When the command execution query is sent to my docker host, I obtain:

* the `com.github.dockerjava.api.InternalServerErrorException: http: Hijack is incompatible with use of CloseNotifier` from my project side,
* a `500 Internal Server Error` with message `http: Hijack is incompatible with use of CloseNotifier` from docker host logs.

Additional information I can provide:

* full logs from project: [arquillian_cube_full_logs.txt](https://github.com/arquillian/arquillian-cube/files/158804/arquillian_cube_full_logs.txt),
* docker logs: [docker_full_logs.txt](https://github.com/arquillian/arquillian-cube/files/158809/docker_full_logs.txt)
* arquillian.xml: [arquillian.xml.txt](https://github.com/arquillian/arquillian-cube/files/158812/arquillian.xml.txt) (please note that removing the database image results in the same issue),
* the same issue occured with Docker 1.8.2 and 1.10.0.

I found that the issue was something already "known":

* [Hijack is incompatible with use of CloseNotifier](https://github.com/docker/docker/issues/12845),
* [Close connection after building or pulling](https://github.com/docker/compose/pull/1374),
* [Dockerpy - Making the container with Python](http://harpoon.readthedocs.org/en/latest/docs/building_harpoon/section1/introduce_dockerpy.html#making-the-container-with-python).

It seems there is a bug in go, causing Docker daemon issues when using a recycled connection.

To try a workaround, I shadowed the `DockerClientExecutor` in order to release the `dockerClient` instance properly (`dockerClient.close()`) after the build request (in the `buildImage` method) and create a new instance of `DockerClient`. Everything is working for me now with such a solution.

Do no hesitate if you need more information about the issue (or if I have not been very understandable ;))!

David.

**Comment by lordofthejars** [comment]
Interesting, I have never seen this error :), one question, do you think it is possible to do a JUnit test using `docker-java` to reproduce the problem?

**Comment by foxlegend** [comment]
Ok, I'll have a try to create such a JUnit test as soon as possible ;)

**Comment by lordofthejars** [comment]
See that it seems it is fixed https://github.com/docker-java/docker-java/issues/471 so if we have the unit test we will be able to test it, or you can wait until we can merge the PR of docker-java https://github.com/arquillian/arquillian-cube/pull/295 and try then :)

**Comment by smiklosovic** [comment]
I have spot this as well:

https://github.com/arquillian/arquillian-cube/issues/290

I do not have the workaround yet. However I have to say that updating to Docker 1.10.2 and using API 1.22 seems to solve this. I have not spot that error anymore ... I am on Arquillian Cube 1.0.0.Alpha7 and Docker 1.10.2.

**Comment by smiklosovic** [comment]
Well, I do not obviously spot this error because I have not been building images :) I have spot this error while I was trying to update Cube to use Docker 1.10.2 so yes, you might still get that exception.

I am wondering if this will be autoresolved while using new docker-java client of that rc2 release ...

**Comment by smiklosovic** [comment]
@foxlegend your investigation went 100% right and that is indeed the problem but I have not run that extra mile to implement the fix you did. Thanks a lot for it!

It would be awesome if you were able to sent a PR where this is solved. I would rather wait for the docker-java alignement first to see it if was not already resolved by it.

**Comment by lordofthejars** [comment]
It seems in rc2 is fixed according to a fixed issue described there

**Comment by lordofthejars** [comment]
We have updated docker-java version to latest ones, in next release would be interesting to try it and see if it is still happens or not.

**Comment by foxlegend** [comment]
Hello !

I had a try with HEAD which contains the merge with PR updating docker-java-version.
Unfortunately, I have the same problem (attached below):

* [arquillian_cube_docker_java_3_stacktrace.txt](https://github.com/arquillian/arquillian-cube/files/167332/arquillian_cube_docker_java_3_stacktrace.txt)

I didn't have the time to create a JUnit, are you still interested?
Are you also interested by a PR with my proposal?

**Comment by lordofthejars** [comment]
Absolutely, we need to find what is happening :) and if you found a possible solution with code maybe we can extrapolate to other situations. Thanks

**Comment by foxlegend** [comment]
Ok, I'll provide this ASAP.

For information, after further investigation it seems to be a problem with go: docker/docker#12845 and golang/go#9763

It should be fixed once docker would be build with go 1.6, and fortunately: docker/docker@14d5c91d87fac962bbb36c12b05f3b1603aa28a8 :) (maybe for Docker 1.11.0).

**Comment by lordofthejars** [comment]
Are you using native Linux Docker or docker-machine?

**Comment by foxlegend** [comment]
I am using something near to boot2docker (a corporate made solution using vagrant).

**Comment by lordofthejars** [comment]
ok, I said this because I talked with one guy that happened the same with native linux docker but installing docker machine on linux and using it, fixed everything

**Comment by lordofthejars** [comment]
hello, how is going the PR?

**Comment by smiklosovic** [comment]
awesome!!! can't wait to try it tomorrow at work ...
